// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHSNgVvxPCFVtJ94rcMjNfc3IKDGpQVs',
    appId: '1:643961249310:web:236f11a78f2c23cc84580f',
    messagingSenderId: '643961249310',
    projectId: 'notesapp-f9472',
    authDomain: 'notesapp-f9472.firebaseapp.com',
    storageBucket: 'notesapp-f9472.firebasestorage.app',
    measurementId: 'G-0P7GFRER9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQcfyhqxYpFGGjJR3ik90iCNzJE4TySY',
    appId: '1:643961249310:android:a10e4a016ec000e284580f',
    messagingSenderId: '643961249310',
    projectId: 'notesapp-f9472',
    storageBucket: 'notesapp-f9472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9S_3rdFEIGyXgZunK1lpsZ6iWMuSijeI',
    appId: '1:643961249310:ios:908aacceba1be39a84580f',
    messagingSenderId: '643961249310',
    projectId: 'notesapp-f9472',
    storageBucket: 'notesapp-f9472.firebasestorage.app',
    iosClientId: '643961249310-3qjfb25ie6nhmqco3ufivc270c8cp2r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9S_3rdFEIGyXgZunK1lpsZ6iWMuSijeI',
    appId: '1:643961249310:ios:908aacceba1be39a84580f',
    messagingSenderId: '643961249310',
    projectId: 'notesapp-f9472',
    storageBucket: 'notesapp-f9472.firebasestorage.app',
    iosClientId: '643961249310-3qjfb25ie6nhmqco3ufivc270c8cp2r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiHSNgVvxPCFVtJ94rcMjNfc3IKDGpQVs',
    appId: '1:643961249310:web:99c44a3f603cb5f484580f',
    messagingSenderId: '643961249310',
    projectId: 'notesapp-f9472',
    authDomain: 'notesapp-f9472.firebaseapp.com',
    storageBucket: 'notesapp-f9472.firebasestorage.app',
    measurementId: 'G-V3L4NP4Q49',
  );
}
